# 笔记

In [1]:
# 导入模块
import pandas as pd
import numpy as np

In [24]:
#### 导入数据集
df = pd.read_csv('module_5_auto.csv')
df.head()

Unnamed: 0  Unnamed: 0.1  symboling  normalized-losses         make  \
0           0             0          3                122  alfa-romero   
1           1             1          3                122  alfa-romero   
2           2             2          1                122  alfa-romero   
3           3             3          2                164         audi   
4           4             4          2                164         audi   

  aspiration num-of-doors   body-style drive-wheels engine-location  ...  \
0        std          two  convertible          rwd           front  ...   
1        std          two  convertible          rwd           front  ...   
2        std          two    hatchback          rwd           front  ...   
3        std         four        sedan          fwd           front  ...   
4        std         four        sedan          4wd           front  ...   

   compression-ratio  horsepower  peak-rpm  city-mpg  highway-mpg    price  \
0                9.0       111.0    5000.0        21           27  13495.0   
1                9.0       111.0    5000.0        21           27  16500.0   
2                9.0       154.0    5000.0        19           26  16500.0   
3               10.0       102.0    5500.0        24           30  13950.0   
4                8.0       115.0    5500.0        18           22  17450.0   

  city-L/100km  horsepower-binned diesel  gas  
0    11.190476             Medium      0    1  
1    11.190476             Medium      0    1  
2    12.368421             Medium      0    1  
3     9.791667             Medium      0    1  
4    13.055556             Medium      0    1  

[5 rows x 31 columns]

## 第一部分：模型训练与评估

### 1. 数据划分为训练数据和测验数据

- 数据提取

In [3]:
y_data = df['price']
x_data = df.drop('price',axis=1)

- 划分训练数据和测试数据

In [5]:
# 导入评估模块
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x_data,y_data,test_size = 0.1,random_state=0)

print(x_train.shape[0])
print(x_test.shape[0])

180
21


- 导入线性回归模型

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
# 建立线性回归模型
lre = LinearRegression()

In [9]:
lre.fit(x_train[['horsepower']],y_train)


LinearRegression()

- 进行评估

In [10]:
lre.score(x_test[['horsepower']],y_test) #测试R方

0.7340722810055448

In [11]:
lre.score(x_train[['horsepower']],y_train) # 训练R方

0.6479796296498318

### 2. 交叉验证得分

In [12]:
# 导入计算模块
from sklearn.model_selection import cross_val_score

In [16]:
# 设置为四叠交叉
Rcross =cross_val_score(lre,x_data[['horsepower']],y_data,cv =4)
# 第一个参数是回归模型，最后一个参数是折叠次数

In [17]:
Rcross

array([0.7746232 , 0.51716687, 0.74785353, 0.04839605])

In [18]:
#平均值
Rcross.mean()

0.522009915042119

In [21]:
# 以负均方差为计算方式
cross_val_score(lre,x_data[['horsepower']],y_data,cv=4,scoring='neg_mean_squared_error')

array([-20254142.84026704, -43745493.26505169, -12539630.34014931,
       -17561927.7224759 ])

### 3. 交叉验证预测

In [22]:
# 导入模块
from sklearn.model_selection import cross_val_predict

In [23]:
#生成预测模型
yhat = cross_val_predict(lre,x_data[['horsepower']],y_data,cv=4)

#进行预测
yhat[0:5]

array([14141.63807508, 14141.63807508, 20814.29423473, 12745.03562306,
       14762.35027598])

## 第二部分：过拟合、欠拟合和模式选择